apiVersion: apps/v1
kind: Deployment
metadata:
  name: "depl"
namespace: test
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
            -name: "map-env"
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: myvariable
            -name: "sec-env"
            valueFrom:
              secretKeyRef:
                name: secrets
                key: variable