apiVersion: v1
kind: Service
metadata:
  name: lab7
  labels:
    app: lab7
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:    
    app: lab7
  type: NodePort