apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    containers:
      - name: myapp
        image: krasyg/ping-app
        env:
        - name: MY_HOST
          valueFrom:
             secretKeyRef:
              name: my-secret
              key: MY_HOST
