apiVersion: batch/v1
kind: Job
metadata:
  name: msg-timer
spec:
  completions: 3
  template:
    metadata:
      name: msg-timer
    spec:
      containers:
      - name: msg-timer
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["echo 'one message to be printed'; sleep 3"]
      restartPolicy: OnFailure


