apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-vol"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

