apiVersion: v1
kind: Pod
metadata:
  name: over-cpu-pod
  namespace: cpu-ns
spec:
  containers:
  - name: over-cpu-pod
    image: vish/stress
    resources:
      limits:
        cpu: "100"
      requests:
        cpu: "100"
    args:
    - -cpus
    - "2"