apiVersion: v1
kind: Pod
metadata:
  name: over-memo-pod
  namespace: limits
spec:
  containers:
  - name: over-memo-pod
    image: polinux/stress
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "50Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]