apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab7
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lab7
  replicas: 1
  template: 
    metadata:
      labels:
        app: lab7
    spec:
      containers:
      - name: lab7
        image: joji95/k8s-static-web-app
        ports:
        - containerPort: 80