apiVersion: v1
kind: Service
metadata:
  name: lab7
  namespace: default
  labels:
    app: lab7
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:    
    app: lab7
  type: NodePort
  
  
