apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  labels:
    app: test-app
spec:
  serviceAccountName: test-user
  containers:
    - name: test-app
      image: bitnami/kubectl
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
