version: "3.9"

services:
  redis:
    image: redis:alpine
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - redis-app:/code
    environment:
      - FLASK_ENV=development
   
