kind: Pod 
apiVersion: v1 
metadata:
  name: test-pod-2
spec:
  volumes:
    - name: my-volume
      configMap:
        name: config-env
  containers:
    - name: container-configmap
      image: krasyg/ping-app
      volumeMounts:
        - name: my-volume
          mountPath: /etc/config
